### ISSUE TITLE
simOUc import issue

### ISSUE THREAD

**Issue by J-Sallis** [bbcho/risktools-dev#9]
pip installed risktools on fresh env - v0.2.4

```python
import risktools as rt

rt.simOU()
```
throws an error where the file risktools\c\simOU.so not found. Looks like the C folder was not included in the latest pypi version. Copy/pasted c folder (dir containing simOU.c/simOU.so) into project dir to see if it worked after manually adding.

Doing this fixes the first issue, function able to find the file simOU.so but throws another error. 
*OSError: [WinError 193] %1 is not a valid Win32 application*
See [here](https://stackoverflow.com/questions/25651990/oserror-winerror-193-1-is-not-a-valid-win32-application)

Setting c arg to false, everything works as expected (using simOUpy func).
```python
rt.simOU(c=False)
```
Will keep looking into this but thought I'd flag

**Comment by bbcho** [comment]
Yeah this is a known issue. I need to change how the C extension is compiled as part of installation. I'm hoping to have it fixed next week. Once it's working it can simulate a 340,000,000 element array in 3.5s.

Thanks for helping!

**Comment by bbcho** [comment]
resolved issue - let me know if it works. New version is 0.2.6.2

**Comment by J-Sallis** [comment]
pip install risktools==0.2.6.2 yields the below error. Appears to be a build issue. Note also tried this on a fresh env.

LINK : error LNK2001: unresolved external symbol PyInit_simOU
      build\temp.win-amd64-cpython-39\Release\src/risktools/c\simOU.lib : fatal error LNK1120: 1 unresolved externals
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\link.exe' failed with exit code 1120

[Error msg](https://learn.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk2001?view=msvc-170)

**Comment by bbcho** [comment]
Try 0.2.6.3

B

**Comment by oailton** [comment]
I faced the same problema as @J-Sallis and it persists on 0.2.6.3
My guess, is that we are using a Windows setup without gcc as the error messages states that the options -fPIC and -shared are unknown to cl.exe (the compiler/linker on Microsoft Visual Studio)
I was able to install the package making some dirty editions to the source (sorry for not having a proper Pull Request). I changed the location of simOU.c to the src folder (as src/risktools/c conflicts with the use of setuptools.find_packages("src") because it will expect a package risktools.c to be there also). So I changed setup.py, extensions-> sources to ["src/simOU.c"]

**Comment by oailton** [comment]
I am using Python 3.9.12 on a Windows 10 machine with Microsoft Visual Studio 2022. I made two other editions to get rid of some warnings:
setup.cfg , changing description-file to description_file
setup.py, changing extra_compile_args to None - but this is really dirty and ONLY works for Microsoft compilers. I would be better to detect if the compiler is msvc or something like that and use None only on this case.

**Comment by bbcho** [comment]
I removed the c extension for now - extension compiles fine in Linux but MSVC seems to cause linking issues.
